config/routes.rb
Rails.application.routes.draw do
  get 'books', to: 'books#mybooks' 
  devise_for :users
  root to: "books#index"
  resources :books do
    resources :reviews do
      resources :comments
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :reviews
  has_many :comments
  has_one_attached :image

  validates :title, :author, :publisher, :description, :image, presence: true 
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review
  belongs_to :user

  validates :content, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user
  has_many :comments

  validates :content, :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
  has_many :reviews
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :email, :family_name, :first_name, :birthday])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :edit, :update, :destroy]
  before_action :move_to_mybooks, except: [:mybooks, :show, :search]
  before_action :move_to_book, only: [:edit]

  def mybooks
    @books = Book.includes(:user)
  end
  
  def index
    if user_signed_in?
      @books = current_user.books
    else
      @books = Book.includes(:user)
    end
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    # binding.pry
    # @comment = Comment.find(params[:comment_id])
    # @comments = @review.comments.includes(:review)
    # @comments = @book.review.comment.all
    # @review = Review.find(params[:id])
    # ↓これは惜しかった
    # @review = @book.reviews[1].comments
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @book.destroy
    redirect_to root_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :description, :author, :publisher, :image).merge(user_id: current_user.id)
  end

  def find_book
    @book = Book.find(params[:id])
  end
  
  def move_to_mybooks
    redirect_to action: :mybooks unless user_signed_in?
  end
  
  def move_to_book
    @book = Book.find(params[:id])
    redirect_to book_path(@book) if @book.user_id != current_user.id
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_book
  before_action :find_review
  before_action :find_comment, only: [:edit, :update, :destroy]

  def new
    @comment = Comment.new
  end
  
  def create
    # binding.pry
    @comment = Comment.new(comment_params)
    @comment.book_id = @book.id
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to book_path(@book)
    else
      render 'new'
    end
  end

  def edit
  end
  
  def update
    if @comment.update(comment_params)
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    redirect_to book_path(@book)
  end

  private

  def comment_params
    @book = Book.find(params[:book_id])
    @review = Review.find(params[:review_id])
    params.require(:comment).permit(:content, :like).merge(user_id: current_user.id, book_id: @book.id, review_id: @review.id)
  end

  def find_book
    @book = Book.find(params[:book_id])
  end

  def find_review
    @review = Review.find(params[:review_id])
  end

  def find_comment
    @comment = Comment.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_book
  before_action :find_review, only: [:edit, :update, :destroy]

  def new
    # binding.pry
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.book_id = @book.id
    @review.user_id = current_user.id

    if @review.save
      redirect_to book_path(@book)
    else
      render 'new'
    end
  end

  def edit
  end

  def show
    # binding.pry
    # @comments = @review.comments
    @review = Review.find(params[:id]).comments.target
  end
  
  def update
    if @review.update(review_params)
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to book_path(@book)
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end

  def find_book
    @book = Book.find(params[:book_id])
  end

  def find_review
    @review = Review.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
  <%#= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
  <%= f.file_field :image, id:"book-img" %>
  <%= f.input :title, label: "Book Title" %>
  <%= f.input :author %>
  <%= f.input :publisher %>
  <%= f.input :description %>
  <%= f.button :submit, value="完了" %>
<% end %>

app/views/books/edit.html.erb
<h1>本の編集</h1>

<%= render 'form' %>
<%= link_to '本の詳細ページへ戻る', book_path(@book) %>

app/views/books/index.html.erb
<h1>Index</h1>

<%= link_to 'ログイン', new_user_session_path %>
<%= link_to '新規登録', new_user_registration_path %>
<%= link_to 'ログアウト', destroy_user_session_path %>

<%= link_to '本棚に追加', new_book_path %>

app/views/books/mybooks.html.erb
<h1>みんなの本棚</h1>

<div class="row">
  <% @books.each do |book| %>
    <div class="col-md-3">
      <a href="/books/<%= book.id%>">
      <%= image_tag book.image, class: "book" %>
      </a>
    </div>
  <% end %>
</div>

app/views/books/new.html.erb
<h1>本の追加</h1>

<%= render 'form' %>

app/views/books/show.html.erb
<h1>本の詳細ページ</h1>
<div class="row">
  <div class="col-md-4">
    <%= image_tag @book.image, class:"book-show" %>
  </div>
  <div class="col-md-8">
    <b>タイトル</b>
    <h3>『<%= @book.title %>』</h3>
    <b>著者</b>
    <h4><%= @book.author %></h4>
    <b>内容：</b>
    <p><%= @book.description %><p>

    <b>レビューの一覧：</b>
    <%# ここにレビュー機能を実装 %>
    <%= render @book.reviews %>
    <%# 上記の書き方は、https://pikawaka.com/rails/partial_template を参照のこと。 %>
  </div>
</div>


<% if user_signed_in? %>
  <ul>
    <li><%= link_to 'この本をレビューする', new_book_review_path(@book) %></li>
  </ul>
<% end %>

<% if user_signed_in? && @book.user_id == current_user.id %>
  <ul>
    <li><%= link_to 'マイ本棚へ戻る', root_path %></li>
    <li><%= link_to '本の内容を編集する', edit_book_path(@book) %></li>
    <li><%= link_to '本棚から削除する', book_path(@book), method: :delete, data: { confirm: "Are you sure?"} %></li>
  </ul>
<% else %>
  <ul>
  <li><%= link_to 'みんなの本棚へ戻る', books_path %></li>
  </ul>
<% end %>

app/views/comments/_comment.html.erb
<b>この投稿へのコメント</b>
<div>
  コメント投稿者：<%= comment.user.nickname %>
</div>
<div>
  コメント：<%= comment.content %>
</div>
<div>
  いいね：<%= comment.like %>
</div>

app/views/comments/_form.html.erb
<%#= simple_form_for([@book, @book.reviews.build]) do |f| %>
<%= simple_form_for([@book, @review, @comment]) do |f| %>
  <%= f.input :like %>
  <%= f.input :content %>
  <%= f.button :submit, value="完了" %>
<% end %>

app/views/comments/edit.html.erb
<h1>edit comment</h1>

<%= render 'form' %>

app/views/comments/new.html.erb
<h1>new comment</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBookshelf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
  <nav class="navbar navbar-default">

      <div class="container">
        <div class="navbar-header">
          <%= link_to 'My BookShelf', root_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li><%= link_to current_user.nickname, root_path %></li>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to '新規登録', new_user_registration_path %></li>
            <li><%= link_to 'ログイン', new_user_session_path %></li>
          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to '本の追加', new_book_path %></li>
            <li><%= link_to 'みんなの本棚', books_path %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" id="dropdownMenuButton">Menu <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li>カテゴリ</li>
              <li>カテゴリ2</li>
            </ul>
          </li>
        </ul>
      </div>
    
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@book, @book.reviews.build]) do |f| %>
  <%= f.input :rating %>
  <%= f.input :content %>
  <%= f.button :submit, value="完了" %>
<% end %>

app/views/reviews/_review.html.erb
<p></p>
<b>レビュー</b>
<p>投稿者：<%= review.user.nickname %></p>
<p>星：<%= review.rating %></p>
<p>投稿：<%= review.content %></p>

<%# rv_counter = Review.find{review_counter}.comments %>
<%#= puts "hello" %>

<div>
  <% if user_signed_in? && review.user_id == current_user.id %>
    <%= link_to 'レビューの編集', edit_book_review_path(review.book, review) %>
    <%= link_to 'レビューの削除', book_review_path(review.book, review), method: :delete, data: {confirm: "Are you sure?"} %>
  <p><%#= link_to 'このレビューへのコメントを表示', book_review_path(Book.find(params[:id]),Review.find{review_counter}.comments) %></p>
  <%= render partial: 'comments/comment', collection: @comments %>
  <% end %>

  <% if user_signed_in? && review.user_id != current_user.id %>
  <p><%#= link_to 'このレビューへのコメントを表示', book_review_path(Book.find(params[:id]),Review.find{review_counter}.comments) %></p>
    <%#= link_to 'このレビューにコメントする', new_book_review_comment_path(Book.find(params[:id]),Review.find{review_counter}.comments) %>
    <%= render partial: 'comments/comment', collection: @comments %>
  <% end %>
</div>

<%#= render @comments %>

app/views/reviews/edit.html.erb
<h1>edit review</h1>

<%= render 'form' %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

app/views/reviews/show.html.erb
<h1>show review</h1>
<b>レビュー</b>
<div>投稿者：<%= @review.user.nickname %></div>
<div>星：<%= @review.rating %></div>
<div>投稿：<%= @review.content %></div>
<p></p>

<%= render partial: 'comments/comment', collection: @comments %>